[package]
name = "rsspal"
version = "0.1.0"
edition = "2021"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nix = "0.26.2"
serenity = "0.11.6"
tokio = { version = "1.21.2", features = ["macros", "rt-multi-thread", "signal"] }
