name: Deploy rsspal

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy rsspal to server
    runs-on: ubuntu-latest
    steps:
      - name: Get latest code
        uses: actions/checkout@v3

      - name: Get ssh key from secrets
        run: install -m 600 -D /dev/stdin $HOME/.ssh/id_25519 <<< "${{ secrets.SSH_PRIVATE_KEY }}"

      - name: Add known hosts to .ssh directory
        run: |
          ssh-keyscan -H "${{ secrets.SERVER }}" > $HOME/.ssh/known_hosts
      
      # Requires sshd on server to AcceptEnv DISCORD_TOKEN
      - name: Run deployment script on server
        run: >
          ssh -o "SendEnv DISCORD_TOKEN"
          "${{ secrets.USER }}@${{ secrets.SERVER }}"
          'sh -ls' < install_script.sh
        env:
          DISCORD_TOKEN: "${{ secrets.DISCORD_TOKEN }}"