name: main

on:
  push:
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

permissions:
  checks: write

jobs:
  build:
    name: Build rsspal
    strategy:
      matrix:
        profile: [dev, release]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
        
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2

      - name: Build
        uses: clechasseur/rs-cargo@v1
        with:
          command: build
          args: --profile ${{ matrix.profile }}

  clippy:
    name: Cargo clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - uses: Swatinem/rust-cache@v2

      - name: Run Clippy
        uses: auguwu/clippy-action@1.2.2
        with:
          all-features: true
          deny: warnings
          token: ${{ secrets.GITHUB_TOKEN }}

  test:
    name: Cargo nextest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          recursive: true

      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2

      - name: Install cargo-nextest
        uses: baptiste0928/cargo-install@v2
        with:
          crate: cargo-nextest

      - name: Run tests
        uses: clechasseur/rs-cargo@v1
        with:
          command: nextest
          args: run
